name: "Check JIRA Ticket"
description: "Verify if a JIRA ticket exists based on the PR title or body"
inputs:
  jiraApiToken:
    description: 'JIRA Service API Token'
    required: true
  jiraServiceUser:
    description: 'JIRA Service User'
    required: true
  jiraServer:
    description: 'JIRA Server URL'
    required: true
  githubToken:
    description: 'Github Token'
    required: true
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/jira-ticket-checker.py
      shell: python